# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test Angular - greyhill-test

on:
  push:
    branches:
      - fix/https-blocknute
  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        working-directory: client
        run: npm install

      - name: ng build production
        working-directory: client
        run: npx ng build --configuration production #nefungovalo na github actions
        #run: ng build --configuration production

      - name: Create ZIP artifact
        working-directory: client
        run: |
          if [ -d "dist" ]; then
            cd dist && zip -r ../release.zip . && cd ..
          else
            echo "ERROR: dist directory not found. Build may have failed."
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: client/release.zip

  deploy-angular:
    runs-on: ubuntu-latest
    needs: build-angular
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D5B35F7E64E41DCAB9F5A636B5EF96F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4D5A26F2EF9468DAE518C8A7DF3CF50 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6B52173F353E40A28F33BB7E03709F3C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-angular-app
        with:
          app-name: 'greyhill'
          slot-name: 'Production'
          package: ./
